export const LOAD_PRODUCTS_BY_CATEGORY = "LOAD_PRODUCTS_BY_CATEGORY";
export const LOAD_PRODUCTS_BY_CATEGORY_ERROR ="LOAD_PRODUCTS_BY_CATEGORY_ERROR"
export const LOAD_PRODUCT_BY_ID = "LOAD_PRODUCT_BY_ID";
export const LOAD_PRODUCT_BY_ID_ERROR = "LOAD_PRODUCT_BY_ID_ERROR";
